segments:
  branch: Branch Evaluation
  contact-centre: Direct Contact Centre Evaluation
  website: Website Evaluation
  social-media: Social Media Evaluation 
  combined-contact-centre: Combined Contact Centre Evaluation