segments:
  branch: Branch Evaluation
  contact-centre: Contact Centre (Direct 800-Chery)
  website: Website Evaluation
  social-media: Social Media Evaluation 
  combined-contact-centre: Combined Contact Centre  (800 Chery+Web+SM)