metric_groups:
  "1 SOCIAL MEDIA RESPONSE/AGENT EVALUATION":
    iQ1: "Q1.Response time to Enquiry"
    iQ2: "Q2.Public response time"
    iQ2a: "Q2a.First response mode (Automated/SM Agent)"
    iQ3: "Q3.SM Agent Greeting"
    iQ4: "Q4.Satisfactory answer to Enquiry by SM Agent"
    iQ5: "Q5.Clarity of SM Agent Communication"
    iQ6: "Q6.Customer information asked"
    iQ9: "Q9.Postive closing remarks"
    iQ9a: "Q9a.Appointment call received"

  "2 CALL AGENT GREETING":
    iQ10b: "Q10b.Background noise level"
    iQ10c: "Q10c.Call greeting type"
    iQ10d: "Q10d.Agent attentiveness level"
    iQ10e: "Q10e.Agent personalization actions"
    iQ10f: "Q10f.Agent's interaction manner"
    iQ10g: "Q10g.Agent's communication clarity"
    iQ10h: "Q10h.Agent's questions asked"
    iQ10i: "Q10i.Agent's actions taken"
    iQ10i_1: "Q10i_1.Agent's response action"
    iQ10k: "Q10k.Agent's appointment confirmation"
    iQ10l: "Q10l.Appointment confirmation received"
    iQ10m: "Q10m.Average call duration"

  "3 SALES CONSULTANT INTERACTION":
    iQ11a: "Q11a.Sales consultant call received"
    iQ11b: "Q11b.Time to contact by consultant"
    iQ11d: "Q11d.Consultant's actions taken"
    iQ11e: "Q11e.Consultant's attentiveness level"
    iQ11f: "Q11f.Consultant's vehicle recommendation"
    iQ11g: "Q11g.Consultant's personalization actions"
    iQ11h: "Q11h.Consultant's interaction manner"
    iQ11i: "Q11i.Consultant's communication clarity"

  "4 OVERALL EVALUATION":
    iQ12a: "Q12a.Follow-up call prior to visit"
    iQ12b: "Q12b.Timiing of that Follow-up call"
    iQ13: "Q13.Overall experience with Social Media"

weight_variables:
  "1 SOCIAL MEDIA RESPONSE/AGENT EVALUATION": wSMAGENTEVAL
  "2 CALL AGENT GREETING": wGREETING
  "3 SALES CONSULTANT INTERACTION": wINTERACTION
  "4 OVERALL EVALUATION": wOVERALLEVALUATION 